version: "3.9"
services:
  api:
    container_name: fastapi_todo_api
    environment:
      - SQLALCHEMY_DB_URL=postgresql://fastapi_todo:fastapi_todo@db:5432/todo
      - SECRET_KEY='D8C013F4063E4CE4A67B3587A45FAD1F6D3241A0EA015C919A9E071CD5AA8273'
      - ALGORITHM='HS256'
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c 'uvicorn fastapi_todo.app:app --host 0.0.0.0 --port 8000 --reload'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db:db
    networks:
      - fastapinetwork
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi_todo
      - POSTGRES_PASSWORD=fastapi_todo
      - POSTGRES_DB=todo
    networks:
      - fastapinetwork

volumes:
  postgres_data:

networks:
  fastapinetwork:
    driver: bridge
